### ISSUE TITLE
spring-security-pac4j for legacy spring MVC apps with spring security?

### ISSUE THREAD

**Issue by frankbe** [pac4j/spring-security-pac4j#104]
I have to extend a legacy spring webmvc application with OIDC capabilities. The application makes a lot use of spring security, so I thought spring-security-pac4j would be the right choice. 

But the I read "For a Spring Boot or Spring MVC project, you should use the spring-webmvc-pac4j library instead of this one". 
I can do that, but I wonder what's the suppose of this library then. Only desktop (respectively non-webmvc) applications? 
Or does it just mean that for **new** projects **without spring security** one should rather use spring-webmvc-pac4j instead of this one?

**Comment by leleuj** [comment]
The `spring-security-pac4j` library is useful if you plan to keep the Spring Security configuration you already have but also add pac4j features (OIDC).
If you plan to migrate all your Spring Security configuration or start a new SpringMVC webapp, you should use the `spring-webmvc-pac4j` library, it's easier (to have one security framework instead of two).

**Comment by frankbe** [comment]
Thank you for the clarification. That helps a lot.

**Comment by frankbe** [comment]
Finally I replaced Spring Security completely with spring-webmvc-pac4j. The nice thing is, I was able to remove at least half of the complexity without any loss of functionality (apart from the JSP taglib parts). Plus a complete OIDC solution using pac4j-oidc, which doesn't seem to exist in Spring Security yet. It was a lot of work, but it was worth it.

**Comment by leleuj** [comment]
I'm glad to hear it!
